apiVersion: v1
kind: ReplicationController
metadata:
  name: errbit
  labels:
    name: errbit
    context: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: errbit
        context: default
    spec:
      containers:
      - name: errbit
        image: griff/errbit
        ports:
        - containerPort: 3000
