apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    name: mongodb-pod
    context: default
spec:
  containers:
    - name: mongodb
      image: mongo:latest
      ports:
        - containerPort: 27017
        - containerPort: 27018
        - containerPort: 27019
        - containerPort: 28017
